### ISSUE TITLE
Fix game crash

### ISSUE THREAD

**Issue by devstopfix** [devstopfix/elixoids#61]
```
     ** (EXIT from #PID<0.240.0>) an exception was raised:
         ** (ArithmeticError) bad argument in arithmetic expression
             :erlang.div(1000, 0)
             (elixoids) lib/world/clock.ex:34: World.Clock.ms_between_frames/1
             (elixoids) lib/game/server.ex:179: Game.Server.initial_game_state/2
             (elixoids) lib/game/server.ex:161: Game.Server.init/1
             (stdlib) gen_server.erl:374: :gen_server.init_it/2
             (stdlib) gen_server.erl:342: :gen_server.init_it/6
             (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by devstopfix** [comment]
Caused by default game having FPS of zero
