### ISSUE TITLE
Fix race condition on spawned ships

### ISSUE THREAD

**Issue by devstopfix** [devstopfix/elixoids#70]
```
[error] GenServer {Registry.Elixoids.Games, {0}} terminating
** (FunctionClauseError) no function clause matching in Game.Server.ship_state_has_tag/2
    (elixoids) lib/game/server.ex:427: Game.Server.ship_state_has_tag(:spawn, "JCJ")
    (elixir) lib/enum.ex:3021: Enum.reject_list/2
    (elixir) lib/enum.ex:3024: Enum.reject_list/2
    (elixoids) lib/game/server.ex:367: Game.Server.fetch_ship_state/2
```

**Comment by devstopfix** [comment]
Fixed in 162aed9f
